pipeline {
    agent any

    stages {
        }
        stage('Preparar entorno') {
            steps {
                sh 'python -m venv venv'
                sh '. venv/bin/activate && pip install -r requirements.txt'
            }
        }
        stage('Ejecutar pruebas') {
            steps {
                sh '. venv/bin/activate && pytest tests/ --html=report.html'
            }
        }
        stage('Publicar reporte') {
            steps {
                publishHTML(target: [
                    reportDir: '.',
                    reportFiles: 'report.html',
                    reportName: 'Reporte de pruebas'
                ])
            }
        }
    }
}
